// <auto-generated />
using AuthServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AuthServer.Models.CustomUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Konya",
                            Email = "User1@mail.com",
                            Password = "12345",
                            Username = "User1"
                        },
                        new
                        {
                            Id = 2,
                            City = "İzmir",
                            Email = "User2@mail.com",
                            Password = "12345",
                            Username = "User2"
                        },
                        new
                        {
                            Id = 3,
                            City = "İstanbul",
                            Email = "User3@mail.com",
                            Password = "12345",
                            Username = "User3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
